### ISSUE TITLE
插件无法加载

### ISSUE THREAD

**Issue by BraisedChick** [BingYanchi/BungeeHub#1]
版本：Waterfall:47c4790
[15:04:13 WARN]: Error loading plugin BungeeHub
java.lang.reflect.InvocationTargetException: null
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_291]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_291]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_291]
        at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_291]
        at net.md_5.bungee.api.plugin.PluginManager.enablePlugin(PluginManager.java:395) ~[server-release.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:fc30291:498]
        at net.md_5.bungee.api.plugin.PluginManager.loadPlugins(PluginManager.java:300) ~[server-release.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:fc30291:498]
        at net.md_5.bungee.BungeeCord.start(BungeeCord.java:278) ~[server-release.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:fc30291:498]
        at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67) ~[server-release.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:fc30291:498]
        at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) ~[server-release.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:fc30291:498]
Caused by: java.lang.NoClassDefFoundError: org/inventivetalent/update/spiget/UpdateCallback
        at cn.yistars.hub.Hub.<init>(Hub.java:22) ~[?:?]
        ... 9 more
Caused by: java.lang.ClassNotFoundException: org.inventivetalent.update.spiget.UpdateCallback
        at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:103) ~[server-release.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:fc30291:498]
        at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:59) ~[server-release.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:fc30291:498]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_291]
        at cn.yistars.hub.Hub.<init>(Hub.java:22) ~[?:?]
        ... 9 more

**Comment by BingYanchi** [comment]
可能是更新检测导致的，你可以先禁用更新检查器
